image: docker:stable

stages:
  - publish

Docker Image:
  stage: publish
  only:
    - master
  before_script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - source .env.dist
  script:
    - docker build --tag "$CI_REGISTRY_IMAGE:$(cat ./VERSION)" --build-arg SOLR_VERSION=${SOLR_VERSION} --rm ./
    - docker push "$CI_REGISTRY_IMAGE"
